version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    # volumes: TODO Add volume for storing images to filesystem
    depends_on:
      - postgres

  postgres:
    image: postgres:11.4
    hostname: postgres
