version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/avatars/:/src/avatars/
    depends_on:
      - postgres

  postgres:
    image: postgres:11.4
    hostname: postgres
